version: '3'
services:
  db: 
    image: mysql
    restart: always
    ports:
      - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'LEARNHUB-BD'
    volumes: 
      - ./data:/var/lib/mysql